/*
 * This file is generated by jOOQ.
 */
package com.example.demo;


import com.example.demo.tables.Library;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.library</code>.
     */
    public static final Library LIBRARY = Library.LIBRARY;
}
