/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.records;


import com.example.demo.tables.Library;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LibraryRecord extends TableRecordImpl<LibraryRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 720164463;

    /**
     * Setter for <code>public.library.id</code>.
     */
    public LibraryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.library.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.library.name</code>.
     */
    public LibraryRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.library.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Library.LIBRARY.ID;
    }

    @Override
    public Field<String> field2() {
        return Library.LIBRARY.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public LibraryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LibraryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LibraryRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LibraryRecord
     */
    public LibraryRecord() {
        super(Library.LIBRARY);
    }

    /**
     * Create a detached, initialised LibraryRecord
     */
    public LibraryRecord(Integer id, String name) {
        super(Library.LIBRARY);

        set(0, id);
        set(1, name);
    }
}
